package carsharing.db;

public enum MenuState {
    START, MANAGER, COMPANY_LIST, CREATE_COMPANY, COMPANY_MENU, CREATE_CAR, CAR_LIST, CUSTOMER_MENU, CREATE_CUSTOMER, CUSTOMER_LIST, RENT_CAR, RETURN_CAR, SHOW_RENTED_CAR, EXIT
}
